---
development:
  cloud_name: dwzrkks74
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dwzrkks74
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dwzrkks74
  enhance_image_tag: true
  static_file_support: false
